### ISSUE TITLE
When adding poll option, make sure there's not too many already 

### ISSUE THREAD

**Issue by abrahammurciano** [abrahammurciano/paul-bot#33]

**Comment by ScreamingHawk** [comment]
I see this was already fixed https://github.com/abrahammurciano/paul-bot/commit/6d1e0379e5e2d76c9b07272fc83bdac7240102ee

Would it be possible to instead overflow the options into another embed?

**Comment by abrahammurciano** [comment]
@ScreamingHawk interesting proposal. I think it wouldn't work because the limit is due to the number of buttons that can be put on a message. More embeds wouldn't fix that.

Spreading it out into more messages might help though, but it would be much more complicated to implement (having to store multiple messages per poll in the database, checking which one contains which options, editing both at a time, etc). I don't think I will implement this

**Comment by ScreamingHawk** [comment]
That's fair. It's a UX nightmare as well
